# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-single:
    if: github.event_name == 'pull_request'
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [ 14.x ]
        os: [ ubuntu-latest ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: bash test.sh
  test-all:
    if: github.event_name == 'push'
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [ 12.x, 14.x, 15.x ]
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: bash test.sh
  deploy:
    needs: test-all
    if: github.event_name == 'push'
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [ 14.x ]
        os: [ ubuntu-latest ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: bash deploy.sh
    
    env:
      GITHUB_REPOSITORY_SLUG: ${{ github.repository }}
      AWS_REGION: us-east-2
